LeokaGroup/LeokaEstetica.Platform.FrontEnd

angular.json, src/app/modules/vacancy/catalog/components/catalog-vacancy.component.html, src/app/modules/vacancy/catalog/components/catalog-vacancy.component.scss, src/app/modules/vacancy/catalog/components/catalog-vacancy.component.ts, testFeature.txt
Добавил счетчик вакансий в каталоге
=> [feature/add-vacancies-count] Добавление счетчика вакансий в каталоге

src/app/app.component.html, src/app/app.component.ts, src/app/modules/administration/administration.module.ts, src/app/modules/administration/components/administration.component.html, src/app/modules/administration/components/administration.component.ts, src/app/modules/moderation/components/moderation/moderation.component.html, src/app/modules/moderation/components/moderation/moderation.component.scss, src/app/modules/moderation/components/moderation/moderation.component.ts, src/app/modules/moderation/models/input/approve-resume-input.ts, src/app/modules/moderation/models/input/reject-resume-input.ts, src/app/modules/moderation/moderation.module.ts, src/app/modules/moderation/services/moderation.service.ts, src/app/modules/notifications/signalr/services/signalr.service.ts, src/app/modules/project/catalog/components/catalog.component.ts, src/app/modules/project/detail/components/detail.component.html, src/app/modules/project/detail/components/detail.component.ts, src/app/modules/project/services/project.service.ts, src/app/modules/vacancy/detail/detail.component.html, src/app/modules/vacancy/detail/detail.component.ts
Reverts LeokaGroup/LeokaEstetica.Platform.FrontEnd#99
=> Revert "делаем удаление в Вакансии проекта"

src/app/modules/project/catalog/components/catalog.component.html, src/app/modules/project/catalog/components/catalog.component.scss, src/app/modules/resume/catalog/components/catalog.component.html, src/app/modules/resume/catalog/components/catalog.component.scss
=> кол-во в каталогах

src/app/modules/backoffice/left-menu/components/left-menu.component.ts, src/app/modules/vacancy/my-vacancy/my-vacancy.component.html, src/app/modules/vacancy/my-vacancy/my-vacancy.component.scss, src/app/modules/vacancy/my-vacancy/my-vacancy.component.ts, src/app/modules/vacancy/services/vacancy.service.ts, src/app/modules/vacancy/vacancy-routing.module.ts, src/app/modules/vacancy/vacancy.module.ts
список вакансии без реализации кнопок
=> создали страницу список вакансии(пока без функционала кнопок)

src/app/modules/moderation/components/moderation/moderation.component.html, src/app/modules/moderation/components/moderation/moderation.component.ts, src/app/modules/moderation/models/input/approve-resume-input.ts, src/app/modules/moderation/models/input/reject-resume-input.ts, src/app/modules/moderation/services/moderation.service.ts
кнопки одобрить удалить и посмотреть не работают еще
=> вывод всех анкет в модерации

src/app/common/styles/spaces.scss, src/app/modules/backoffice/aboutme/components/aboutme.component.html, src/app/modules/backoffice/vacancy/detail/detail.component.html, src/app/modules/project/detail/components/detail.component.html, src/app/modules/project/detail/components/detail.component.scss
Также вошли задачи:
#27661558 Заменять оплату вакансии, если стоит 0 на "Нет оплаты".
=> #27661430 Поправить табуляцию в просмотре проекта.

src/app/modules/project-managment/services/project-managment.service.ts, src/app/modules/project-managment/task/components/task-details/task-details.component.html, src/app/modules/project-managment/task/components/task-details/task-details.component.ts, src/app/modules/project-managment/task/models/input/project-task-executor-input.ts, src/app/modules/project-managment/task/models/input/project-task-watcher-input.ts
=> #28262979 Реализовать изменение и сохранение наблюдателей задачи.

src/app/modules/Enums/task-detail-type.ts, src/app/modules/project-managment/project-managment-routing.module.ts, src/app/modules/project-managment/project-managment.module.ts, src/app/modules/project-managment/services/project-managment.service.ts, src/app/modules/project-managment/start/components/space/space.component.html, src/app/modules/project-managment/start/components/space/space.component.ts, src/app/modules/project-managment/task/components/epic/epic-details.component.html, src/app/modules/project-managment/task/components/epic/epic-details.component.scss, src/app/modules/project-managment/task/components/epic/epic-details.component.ts, src/app/modules/project-managment/task/components/task-details/task-details.component.html, src/app/modules/project-managment/task/components/task-details/task-details.component.scss, src/app/modules/project-managment/task/components/task-details/task-details.component.ts
В рамках задачи нужно сделать подтягивание всех данных эпика при его просмотре.
=> #30957036 В деталях задачи сделать переход к просмотру эпика.

src/app/modules/backoffice/aboutme/components/aboutme.component.html
#31977612 При редактировании анкеты. Обязательное поле 'номер телефона' не отмечено звездочкой (*)
=> #31977612 Added label - mandatory field 'phone number'

src/app/modules/header/components/header.component.html, src/app/modules/header/components/header.component.scss
#32026909 Отсутствует курсор поинтер
=> #32026909 Added cursor pointer

src/app/modules/backoffice/aboutme/components/aboutme.component.html, src/app/modules/backoffice/aboutme/components/aboutme.component.scss
В режиме просмотра анкеты убрано отображение маркеров обязательности полей
=>  [#31956557] В режиме просмотра анкеты убрано отображение маркеров обязательности полей

src/app/modules/project-managment/backlog/planing/planing.component.html
Устранено раннее появление левой панели
=> [#31967187] Устранено раннее появление левой панели

src/app/modules/backoffice/aboutme/components/aboutme.component.html, src/app/modules/footer/components/footer.component.html
Добавил_тикет_из_футера_в_техподдержку
=> [#24107503]_Добавил_тикет_из_футера_в_техподдержку

src/app/modules/project-managment/task/components/task-details/task-details.component.ts
Дубли при добавлении тегов к задаче
=> [32111492] Дубли при добавлении тегов к задаче

src/app/modules/project-managment/task/components/create-task/create-task.component.html
!! **Работает только если есть ProjectId**
=> #31933256 Сделал проверку на исполнителя

src/app/modules/backoffice/vacancy/detail/detail.component.ts
В функцию onUpdateVacancyAsync() добавлен роутинг на страницу /vacancies/my
=> [#33107890] Добавлен роутинг к списку вакансий пользователя после сохранения изменений вакансии

src/app/modules/backoffice/project/my-projects/components/my-projects.component.html
=> [#34368054] Реализовал применение тегов в описание  в таблице проектов

src/app/modules/project/detail/components/detail.component.html
исправлены зависимости в структурных директивах на странице проекта
=> [#33717011] Исправлено отображение описания проекта

src/app/app.component.html, src/app/app.component.ts
Баг https://leoka-estetica.kaiten.ru/space/136132/lists/card/33034273
Желательно протестировать в тех местах где была похожая проблема
=> [#33034273] Поправил баг с пропаданием левого меню посперехода из УП

src/app/modules/project-managment/header/components/project-management-header.component.html, src/app/modules/project-managment/header/components/project-management-header.component.scss, src/app/modules/project-managment/header/components/project-management-header.component.ts, src/app/modules/project-managment/services/project-managment.service.ts
1) Добавил отображение название проекта, который выбран для управления в модуле УП (f0642e67257703a67c9903a131ea4874f5311169)
2) Добавил  в отображение названия выбранного проекта добавил шрифт соответствующий h5 (17fd907173d954ac2c9c5b9afa229133cb9de917)
=> #34460898 Добавил отображение название проекта, который выбран для управления в модуле УП

src/app/modules/project-managment/sprint-details/components/sprint-details.component.scss, src/app/modules/project-managment/sprint/components/sprint.component.html, src/app/modules/project-managment/sprint/components/sprint.component.scss
=> [#33145082] отцентрованы элементы таблицы "cпринты проекта"

src/app/modules/project-managment/models/input/update-folder-name-input.ts, src/app/modules/project-managment/services/project-managment.service.ts, src/app/modules/project-managment/wiki/components/wiki.component.html, src/app/modules/project-managment/wiki/components/wiki.component.scss, src/app/modules/project-managment/wiki/components/wiki.component.ts
=> #34682939 Добавление возможности переименовать папку в дереве wiki.

src/app/modules/project-managment/models/input/update-folder-name-input.ts, src/app/modules/project-managment/models/input/update-folder-page-description-input.ts, src/app/modules/project-managment/models/input/update-folder-page-name-input.ts, src/app/modules/project-managment/services/project-managment.service.ts, src/app/modules/project-managment/wiki/components/wiki.component.html, src/app/modules/project-managment/wiki/components/wiki.component.scss, src/app/modules/project-managment/wiki/components/wiki.component.ts
=> #34682945 Добавление возможности переименовать страницу в дереве wiki.

angular.json, src/app/modules/project-managment/workspace/components/workspace.component.html, src/app/modules/project-managment/workspace/components/workspace.component.scss, src/assets/styles/layer.scss, src/index.html, src/styles.scss
1. Исправлено отображение стилей PrimeNG
В 17 angular добавили слои css, из-за чего наши стили перетирались стилями normalize.css из bootstrap (подробнее https://stackoverflow.com/questions/77236338/bootstrap-reboot-scss-overriding-primeng-styles)
2. Исправлена ошибка отображения списка пространств проектов в  управлении проектами
В процессе перехода primeng с 13 на 17.18.1 версии было изменено апи компонента DataView
=> [#34595065] Исправлено отображение PrimeNG в angular v17

src/app/modules/project-managment/wiki/components/wiki.component.html, src/app/modules/project-managment/wiki/components/wiki.component.scss
https://leoka-estetica.kaiten.ru/space/136132/card/34858042
=> #34858042-Сделал поле названия папки больше в wiki

src/app/modules/project/detail/components/detail.component.html, src/app/modules/project/detail/components/detail.component.scss
https://leoka-estetica.kaiten.ru/space/136132/card/34668842
=> 34668842-Добавил комментариям проекта кнопку для  отправки сообщения с текстом "Отправить" 

src/app/modules/project-managment/wiki/components/wiki.component.html, src/app/modules/project-managment/wiki/components/wiki.component.scss, src/app/modules/project-managment/wiki/components/wiki.component.ts
=> #34682948 Добавление возможности создать папку/страницу в дереве wiki.

src/app/modules/project-managment/task/components/task-details/task-details.component.html, src/app/modules/project-managment/task/components/task-details/task-details.component.scss
https://leoka-estetica.kaiten.ru/space/136132/card/35129342
=> 35129342 -Увеличить длину поля названия задачи

src/app/modules/project/detail/components/detail.component.html
=> #34502579 Вакансии со статусом модерации и архивные не должны отображаться в таблице проекта для других пользователей.

src/app/modules/project-managment/task/components/task-details/task-details.component.html
Исправлена работа кнопки роутинга на детали эпика
=> [#30957036]: В деталях задачи сделан переход к просмотру эпика

src/app/modules/project/detail/components/detail.component.html
Исправлена ширина отображения полей "Описание проекта" и "Название проекта" при наборе от 170 до 260 знаков без пробелов
=> [#36547878]: Исправлено отображение полей "Описание проекта" и "Название проекта" при просмотре проекта

src/app/modules/project-managment/backlog/planing/planing.component.html, src/app/modules/project-managment/backlog/planing/planing.component.ts
- **Исправлено отображение страниц в пагинаторе** (https://github.com/LeokaGroup/LeokaEstetica.Platform.FrontEnd/commit/c68df58a2f06ebb0f42e07689acdde502f1ad010)
Дополнительно:
- **Исправлено дублирование задач в таблице** (https://github.com/LeokaGroup/LeokaEstetica.Platform.FrontEnd/commit/ac4d705dc106b76c4613e3bbef23122302464326)
=> [#36487525] При планировании спринта исправлено отображение пейджинга включенных задач в спринт

src/app/modules/moderation/callcenter.module.ts, src/app/modules/moderation/components/callcenter/callcenter.component.html, src/app/modules/moderation/components/callcenter/callcenter.component.ts
Изменил p-megamenu на p-menubar, т.к. у megamenu нет authDisplay
=> #36487480 В КЦ меню не должно при наведении открываться

src/app/modules/landing/components/landing.component.html
Изменил шаблон аккордеона для обхода бага данной версии PrimeNG
=> #36910780 [Главная страница] - В блоке "Частые вопросы" при клике на сам вопрос он периодические не раскрывается с первого раза.

src/app/modules/resume/catalog/components/catalog.component.html, src/app/modules/resume/catalog/components/catalog.component.ts
+ заменил компонент p-message на p-messages чтобы отображались стили
=> #36879757 Актуализировать названия тарифов в уведомлении в анкете

src/app/modules/backoffice/aboutme/components/aboutme.component.html
Добавил условие для показа кнопки только при редактировании
=> #37012705 В просмотре анкеты не должно быть кнопки "Сохранить"

src/app/modules/project-managment/task/components/task-details/task-details.component.html, src/app/modules/project-managment/task/components/task-details/task-details.component.ts
=> #37065359 В эпике не добавляется задача в таблицу после ее выбора в выпадающем списке

src/app/modules/project-managment/services/project-managment.service.ts, src/app/modules/project-managment/task/components/create-task/create-task.component.ts, src/app/modules/project-managment/task/components/task-details/task-details.component.ts
Добавил передачу projectId в запрос тегов
=> #35974656 В выпадающем списке меток отображаются метки со всех проектов всех пользователей при создании задачи.

src/app/modules/project-managment/task/components/task-details/task-details.component.html, src/app/modules/project-managment/task/components/task-details/task-details.component.scss
=> #37065505 Увеличить поле поиска задач в эпике до 400-500 рх

src/app/modules/backoffice/aboutme/components/aboutme.component.html
Обновлена верстка компонента анкеты
- добавлено отображение ярлыков для инпутов на странице редактирования анкеты
=> [#37012558]: На странице редактирования анкеты добавлен label над каждым полем

src/app/modules/project-managment/task/components/create-task/create-task.component.scss
=> #36820039 При создании задачи значки в выпадающих списках перекрывают текст

src/app/modules/project-managment/task/components/task-details/task-details.component.html, src/app/modules/project-managment/task/components/task-details/task-details.component.ts
=> #37113416 Добавить блок Agile в задачу как сделано в ошибке

src/app/modules/project-managment/task/components/task-details/task-details.component.html, src/app/modules/project-managment/task/components/task-details/task-details.component.ts
=> #37113420 Добавить блок Agile в эпик как сделано в ошибке, но без выпадающего списка "Добавить в эпик"

src/app/modules/project-managment/task/components/task-details/task-details.component.ts
=> #36490502 Добавить переход к просмотру задачи из задач эпика

src/app/modules/project-managment/task/components/task-details/task-details.component.html, src/app/modules/project-managment/task/components/task-details/task-details.component.ts
Исправил сохранение описания задачи
=> #37265831 Не сохраняется описание задачи при внесении в уже существующую задачу

src/app/modules/project-managment/task/components/create-task/create-task.component.html, src/app/modules/project-managment/task/components/create-task/create-task.component.ts
Исправил добавление и удаление тэгов при создании задачи
=> #31967216 Не сохраняются метки в задачах, эпиках, историях

src/app/modules/user/signin/components/signin.component.html
=> #10078955 Добавить возможность восстановления пароля

src/app/modules/project-managment/project-settings/components/project-settings.component.html, src/app/modules/project-managment/project-settings/components/project-settings.component.ts, src/app/modules/project/detail/components/detail.component.html, src/app/modules/project/detail/components/detail.component.ts
Убрал выбор типа приглашения пользователя
=> #35464364 Продумать по UX, как избавиться от лишнего блока в приглашениях пользователей

src/app/modules/project/detail/components/detail.component.html, src/app/modules/project/detail/components/detail.component.ts, src/app/modules/project/project.module.ts, src/app/modules/project/services/project.service.ts
редактирование 
просмотр владельцем 
просмотр чужого проекта
=> #36035723 Добавление в возможные действия проекта возможности изменения видимости проекта (отображается лишь владельцу)

src/app/modules/backoffice/aboutme/components/aboutme.component.ts
Удалил варнинг о неполном заполнении после успешного сохранения анкеты
=> #36744848 После изменения анкеты после регистрации не удалились уведомления (и не отображать успешное уведомление тут)

src/app/modules/project-managment/task/components/task-details/task-details.component.html, src/app/modules/project-managment/task/components/task-details/task-details.component.ts
=> #37113602 Добавить кнопку "Перейти к спринту" в блок Agile в задачах

src/app/modules/project-managment/left-panel/left-panel.component.ts
=> #37458347 Сделать недоступным пункт бэклога пока не выбран проект в общем пространстве

src/app/app-routing.module.ts, src/app/core/guards/auth.guard.ts, src/app/core/interceptors/network-interceptor.ts, src/app/modules/header/components/header.component.ts
1. Убрал вызов редиректа после navigate
2. Добавил guard на загрузку модулей, которые требуют авторизации
=> #37446137 Поправить мелькание экрана при входе на авторизацию и регистрацию

src/app/modules/project-managment/project-settings/components/project-settings.component.ts
Исправил обновление списка приглашений
=> #36672280 Обновлять таблицу приглашений на фронте после отправки приглашения

src/app/app.component.ts
=> #35591666 Не скрывается левое меню

src/app/modules/project-managment/task/components/task-details/task-details.component.html, src/app/modules/project-managment/task/components/task-details/task-details.component.ts
Убрал запрос на бэк и показ приоритета при редактировании истории
=> #37560063 У истории не должно быть приоритета

src/app/modules/project-managment/task/components/task-details/task-details.component.html, src/app/modules/project-managment/task/components/task-details/task-details.component.ts
Мержить после https://github.com/LeokaGroup/LeokaEstetica.Platform.FrontEnd/pull/622
=> #37593724 У эпика не должно быть приоритета

src/app/modules/user/signin/components/signin.component.html, src/app/modules/user/signup/components/signup.component.html, src/app/modules/user/user.module.ts
=> #35994634 Добавить функцию парольного глаза в форму регистрации и авторизации

src/app/modules/project-managment/project-settings/components/project-settings.component.ts
Сделал обновление ролей даже при ошибке сохранения
=> #36992870 После обновления роли пользователю проекта в ролевой модели, подгружать список ролей пользователя для их актуализации

src/app/modules/backoffice/aboutme/components/aboutme.component.html, src/app/modules/backoffice/aboutme/components/aboutme.component.scss
Изменил маску ввода номера телефона
=> #36744962 Добавить маску на номер телефона (не позволять сохранить анкету с невалидным номером)

src/app/common/styles/color.scss, src/app/common/styles/control.scss, src/app/modules/header/components/header.component.html, src/app/modules/header/components/header.component.scss, src/app/modules/header/components/header.component.ts, src/app/modules/user/signin/components/signin.component.html, src/app/modules/user/signin/components/signin.component.scss, src/app/modules/user/signin/components/signin.component.ts, src/app/modules/user/signup/components/signup.component.html, src/app/modules/user/signup/components/signup.component.scss, src/app/modules/user/signup/components/signup.component.ts
Сделал формы авторизации и регистрации
Поправил верхнее меню - кнопки вход и регистрация меняются для разных форм местами
Добавил валидацию форм
=> #37602566 Улучшение UI формы регистрации и авторизации

src/app/modules/project-managment/task/components/task-details/task-details.component.html, src/app/modules/project-managment/task/components/task-details/task-details.component.scss, src/app/modules/project-managment/task/components/task-details/task-details.component.ts
Сделал показ эпика в котором находится задача
=> #30957031 Отображать в деталях задачи эпик, в котором находится задача

src/app/common/styles/control.scss
=> #37595831 В вакансии в описании, условиях и требованиях сделать перенос по словам, а не по символам

src/app/app.component.ts
=> #36852111 Добавить уведомления

src/app/modules/moderation/components/callcenter/callcenter.component.html, src/app/modules/moderation/components/callcenter/callcenter.component.ts
Сделал сброс чекбоксов замечаний
=> #10222317 Сбрасывать чекбоксы замечаний и массив замечаний при выборе другого проекта для просмотра в модерации

src/app/common/styles/control.scss, src/app/common/styles/font.scss, src/app/modules/project/catalog/components/catalog.component.html, src/app/modules/project/catalog/components/catalog.component.scss
1. Добавил файл font.scss для подключения шрифтов в одном месте
2. Стилизовал кнопку сброса фильтров
=> #37409137 Изменить кнопку на ссылку в каталоге проектов

src/app/common/styles/color.scss, src/app/common/styles/control.scss, src/app/modules/project-managment/task/components/create-task/create-task.component.html
Добавил маркеры обязательных полей
=> #36487447 Увеличить ширину поля поиска, добавить маркеры обязательным полям при создании задачи

src/app/modules/project-managment/task/components/create-task/create-task.component.html, src/app/modules/project-managment/task/components/create-task/create-task.component.scss
Увеличил высоту поля названия задачи
=> #35845203 Сделать высоту поля названия задачи при ее создании больше по высоте

src/app/modules/project-managment/start/components/space/space.component.html, src/app/modules/project-managment/start/components/space/space.component.ts
=> #35145452 Добавить выпадающее меню для многоточий доп.действий в Kanban

src/app/modules/backoffice/backoffice.module.ts, src/app/modules/backoffice/project/create-project/components/create-project.component.html, src/app/modules/backoffice/project/create-project/components/create-project.component.ts, src/app/modules/backoffice/project/create-project/models/input/create-project-input.ts, src/app/modules/project/detail/components/detail.component.ts, src/app/modules/project/detail/models/input/update-project-input.ts, src/app/modules/project/services/project.service.ts
Добавил свитчер (приват, паблик) при создании проекта
=> #37905387 Добавить свитчер (приват, паблик) при создании проекта

src/app/modules/project-managment/project-managment.module.ts, src/app/modules/project-managment/sprint/components/sprint.component.html
=> #30577400 Добавить разделение на отдельные табы на странице спринтов

src/app/modules/backoffice/project/create-project/components/create-project.component.html, src/app/modules/project/detail/components/detail.component.html
Добавил иконки с пояснениями на переключатели видимости проекта
=> #37905358 Добавить иконку i с пояснением на свитчер при редактировании проекта

src/app/modules/project-managment/backlog/planing/planing.component.html, src/app/modules/project-managment/backlog/planing/planing.component.scss
Добавил отметку обязательного поля в название спринта
=> #33304981 Добавить маркеры обязательным полям при планировании спринта

src/app/modules/resume/catalog/components/catalog.component.html, src/app/modules/resume/catalog/components/catalog.component.ts
Убрал мелькание сообщения о доступе
=> #37455557 Избежать мелькания надписи об отсутствии доступа к базе резюме без платной подписки

src/app/modules/backoffice/vacancy/create/create.component.scss
Исправил ширину поля выбора проекта в создании вакансии
=> #38077871 Сделать выпадающий список меньше по длине при создании вакансии

src/app/modules/project-managment/start/components/start/start-project-managment.component.ts
Установил первый шаблон проекта выбранным по-умолчанию
=> #38157830 Проставлять по дефолту первый шаблон при первичной настройке шаблона проекта

src/app/modules/project-managment/header/components/project-management-header.component.scss
=> #38177520 Убрать выделение фоном верхнюю панель модуля УП

src/app/modules/project-managment/header/components/project-management-header.component.html, src/app/modules/project-managment/header/components/project-management-header.component.scss
=> #38163435 Увеличил ширину поля поиска

src/app/modules/project-managment/task/components/task-details/task-details.component.scss
Изменил длину названия задачи и добавил перенос слов
=> #38163851 Слишком длинное название задачи, сделать меньше длину поля и перенос по словам

src/app/modules/moderation/components/callcenter/callcenter.component.html
Убрал повтор номера телефона в модерации анкет
=> #38246229 В модерации анкет дублируется блок номер телефона

src/app/modules/project-managment/task/components/task-details/task-details.component.ts
Исправил добавление задачи в эпик
=> #37113280 Задачу с типом "Ошибка" нельзя добавить в эпик через блок "Agile"

src/app/modules/project-managment/backlog/planing/planing.component.html, src/app/modules/project-managment/backlog/planing/planing.component.ts
Сделал запрет множественного выбора типа поиска задач в спринте
=> #38360788 Запретить выбор множественного выбора чекбоксов в планировании спринта при добавлении задач в спринт

src/app/modules/project/detail/components/detail.component.html, src/app/modules/project/detail/components/detail.component.scss
Поправил верстку формы редактирования проекта
=> #37002499 [Мои проекты] - Поля "Описание проекта", "Требования", "Условия", вышли за границу формы "Изменение информации о проекте".

src/app/modules/project-managment/task/components/task-details/task-details.component.ts
Фикс ошибки проверки ролей (не передавался companyId).
=> #38230629 Нельзя изменить описание уже созданной истории.

package-lock.json, package.json
Обновил PrimeNG до версии 17.18.9
=> #38450748 Отображать текст с бэка с форматированием в editor компоненте

src/app/modules/project-managment/wiki/components/wiki.component.ts
Сделал установку начального состояния и сохранение состояния открытости папок
=> #35318625 После удаления или создания папки/страницы, все дерево схлопывается

src/app/modules/project-managment/sprint/components/sprint.component.html, src/app/modules/project-managment/sprint/components/sprint.component.scss
Изменил вывод спринтов в соответствии с изменениями на бэке
=> #38357868 Внести изменения в эндпоинте, получающего список спринтов. Front

src/app/modules/project-managment/wiki/components/wiki.component.html, src/app/modules/project-managment/wiki/components/wiki.component.ts
Сделал сообщение о пустом дереве wiki
=> #38678178 Если в дереве wiki проекта нет папок вообще, то отображать на русс текст "Нет папок или страниц. Добавьте первую папку или страницу."

src/app/common/styles/color.scss, src/app/common/styles/font.scss, src/app/modules/landing/components/landing.component.html, src/app/modules/landing/components/landing.component.scss
Поправил дизайн блока часто задаваемых вопросов
=> #37553369 Улучшение UI Landing - блок частые вопросы

src/app/common/styles/color.scss, src/app/common/styles/control.scss, src/app/modules/project-managment/backlog/components/backlog.component.html
Добавил в бэклог тултипы и стилизовал их в соответствии с макетом
=> #38910322 Добавить тултипы кнопкам в бэклоге

src/app/modules/project-managment/task/components/create-task/create-task.component.html, src/app/modules/project-managment/task/components/task-details/task-details.component.html
Переместил блок кнопок в создании и в редактировании задач
=> #38910140 Сделать везде расположение кнопок аналогично как при планировании спринта (кнопки в создании и в просмотре задач всех типов)

src/app/modules/project-managment/task/components/task-details/task-details.component.html, src/app/modules/project-managment/task/components/task-details/task-details.component.ts
Скрыл кнопку отправки при пустом комментарии
=> #38910845 Отображается кнопка отправки комментария к задачи, но комментарий еще не заполнен

src/app/modules/project-managment/wiki/components/wiki.component.ts
Поправил обновление дерева после удаления элемента
=> #39023564 После удаления страницы в дереве, дерево не обновляется

src/app/modules/header/components/header.component.ts
Сделал скрытие аватар-меню при логауте
=> #39170887 При разлогине не скрывается профиль в хидере

src/app/modules/project-managment/sprint-details/components/sprint-details.component.scss
Увеличил ширину поля названия спринта
=> #38359009 Увеличить ширину поля при изменении названия спринта

src/app/modules/project-managment/wiki/components/wiki.component.html, src/app/modules/project-managment/wiki/components/wiki.component.ts
Поправил закрытие диалогов создания страниц и папок
=> #39160415 При отмене модалки создания папки wiki она не закрывается

src/app/app.component.ts
=> #39407978 Добавить уведомления. Front

src/app/modules/backoffice/aboutme/components/aboutme.component.html, src/app/modules/backoffice/aboutme/pipes/phone-format.pipe.ts, src/app/modules/backoffice/backoffice.module.ts
Сделал форматирование номера телефона в просмотре анкеты
=> #39453682 Добавить форматирование номеру телефона в просмотре анкеты

src/app/modules/user/signup/components/signup.component.html, src/app/modules/user/signup/components/signup.component.scss, src/app/modules/user/user.module.ts
Добавил подсказку с требованиями к паролю
=> #39041689 Добавить подсказку о требовании пароля при регистрации

src/app/app.component.ts, src/app/core/guards/auth.guard.ts
Исправил переход на форму восстановления пароля
=> #38973327 Нет перехода в форму восстановления пароля после клика по ссылке "Забыли пароль?" в форме "Войти"

src/app/modules/calendar/calendar-employee/components/calendar-employee.component.html
Убрал маркеры обязательных полей из просмотра
=> #39657463 Добавить маркеры обязательности при создании события календаря (в просмотре они не должны отображаться)

src/app/modules/user/signin/components/signin.component.ts
=> #38429305 Исправить опечатку в уведомлении при неверном e-mail во время входа

src/app/modules/calendar/calendar-employee/components/calendar-employee.component.html
Исправил получение статуса пользователя
=> #39389237 Подтягивать статус в выпадающий список текущего пользователя в просмотре события

src/app/modules/project-managment/wiki/components/wiki.component.ts
Убрал показ удаленной папки/старницы после удаления
=> #39170233 Сбрасывать фокус с удаленной страницы/папки в wiki

src/app/modules/calendar/calendar-employee/components/calendar-employee.component.ts
Отключил отбработчик по клику на дату без события
=> #39793553 В календаре при клике на пустой день (без события) открывается модалка события

src/app/modules/user/signin/components/signin.component.scss, src/app/modules/user/signup/components/signup.component.scss
Отцентровал формы входа/регистрации
=> #39642585 Форма авторизации/регистрации должна быть строго по центру экрана

src/app/modules/header/components/header.component.html, src/app/modules/header/components/header.component.ts
Исправил работу верхнего меню в КЦ
=> #39662596 В КЦ не работают пункты меню профиля пользователя (выйти и тд)

src/app/common/styles/color.scss, src/app/modules/moderation/components/callcenter/callcenter.component.html, src/app/modules/moderation/components/callcenter/callcenter.component.scss
Сделал выделение цветом для оплаченых вакансий в КЦ
=> #37063759 Добавить в КЦ вакансиям, которые уже были оплачены выделение цветом

src/app/modules/backoffice/aboutme/pipes/phone-format.pipe.ts
=> #39688951 Кривое форматирование номера телефона в просмотре (возможно и в изменении)

src/app/modules/project-managment/wiki/components/wiki.component.ts
Добавил обновление дерева после переименования страницы
=> #34858857 Не обновляется название страницы в дереве, после его изменения в просмотре страницы

src/app/modules/project-managment/task/components/create-task/create-task.component.html
Изменил сообщение при отсутствии меток
=> #38155643 При создании задачи (с типом задача) не пришел список меток. Статус с бэка 200

angular.json, src/app/modules/project-managment/project-settings/components/project-settings.component.html, src/app/modules/project-managment/project-settings/components/project-settings.component.ts, src/app/modules/project/detail/components/detail.component.html, src/app/modules/project/detail/components/detail.component.ts, src/app/modules/project/project.module.ts, src/app/modules/search/services/search-project-service.ts
=> #39924892 При добавлении пользователя в проект, уведомление о не существующем пользователе появляется до нажатия кнопки отправки приглашения

src/app/modules/calendar/calendar-employee/components/calendar-employee.component.html
Сделал блокировку бэка у диалогов в календаре
=> #39659948 Левое меню накладывается на даты календаря (невозможно выбрать пункт левого меню)

src/app/modules/backoffice/notification/components/notifications.component.html
Добавил в уведомления емэйл и название вакансии
=> #37574064 Повысить информативность уведомления у владельца о приглашении участника в проект

src/app/app.component.ts
=> #40417075 Обрабатывать потерю соединения сокетов

src/app/modules/order-form/select-subscription-plan/select-subscription-plan.component.html
Изменил показ цены на форматированный
=> #37788556 Разбивать цену тарифа на разряды

src/app/modules/project-managment/services/project-managment.service.ts, src/app/modules/project-managment/start/components/space/space.component.html, src/app/modules/project-managment/start/components/space/space.component.scss, src/app/modules/project-managment/start/components/space/space.component.ts
=> #39640381 Активная стратегия представления должна иметь фокус

src/app/modules/project-managment/settings/components/settings.component.html, src/app/modules/project-managment/settings/components/settings.component.scss
Проблема была в том, что меню настроек перекрывалось левым меню.
=> #40296678 Не отображается страница настроек представлений

src/app/app.component.ts, src/app/modules/communications/chat-communications/chat-communications.component.html, src/app/modules/communications/chat-communications/chat-communications.component.scss, src/app/modules/communications/chat-communications/chat-communications.component.ts, src/app/modules/communications/services/communications.service.ts
В рамках задачи также делаю (т.к. они связаны):
#40444848 Разграничить создание диалога компании и диалога проекта.
=> #40445196 Реализовать разграничение при получении диалогов (в зависимости от выбранной группировки диалогов).
